### PR TITLE
New "run_project_build" action and default config value improvements

### PR DESCRIPTION
**Pull request by Kami**
This pull request includes two changes:

1. Fix / specify default value for ``host`` config option. This way it works out of the box for public (non on premise enterprise) Circle CI projects

2. Add new ``run_project_build`` action which allows user to trigger a build for all the workflows for a particular project which utilizes workflows v2.

Existing ``run_build`` job doesn't work with new v2.0 workflows.

### CODE REVIEW

**Comment by Kami** [comment]
There is a small chance I will have the time to work on tests in the near future.

Test failure also doesn't appear to be related to my change. It looks like it was failing before already, but this wasn't not detected by the weekly builds since they don't seem to be running correctly.

Weekly builds don't seem to respect ``FORCE_CHECK_ALL_FILES`` environment variable. No idea how long that has been broken.

**Comment by Kami** [comment]
I pushed two new actions - list_pipelines and wait_until_pipeline finishes.

Those actions utilize API v2. I will add changelog entry, etc. later.

**Comment by Kami** [comment]
While at it, I also pushed some Python 3 compatibility improvements and fixed - e399dd7fb849add002457d3c859a8067a9167d20, 74abd4f63851db506a96a85cb123c2d85390705d.

I believe the second one should fix Python 3 failure (which already existed before any of my changes, but we didn't detected them because of the broken weekly builds aka https://github.com/StackStorm-Exchange/ci/pull/86).

**Comment by Kami** [comment]
(There are some more build failures related to pylint not detecting dynamically added properties by six. I will fix those later. Sadly we can't upgrade to newer version of pylint until we still support Python 2.7)

**Comment by nmaludy** [comment]
@Kami ```
Using config file /home/circleci/ci/lint-configs/python/.pylintrc-exchange
************* Module run_project_build
E: 42,40: Module 'http.client' has no 'OK' member (no-member)
E: 42,56: Module 'http.client' has no 'CREATED' member (no-member)
************* Module get_build_number
E: 19,35: Module 'http.client' has no 'OK' member (no-member)
************* Module wait_until_build_finishes
E: 23,39: Module 'http.client' has no 'OK' member (no-member)
************* Module get_build_info
E: 18,35: Module 'http.client' has no 'OK' member (no-member)
************* Module wait_until_pipeline_finishes
E: 32,35: Module 'http.client' has no 'OK' member (no-member)
************* Module cancel_build
E: 18,35: Module 'http.client' has no 'CREATED' member (no-member)
************* Module retry_build
E: 18,35: Module 'http.client' has no 'CREATED' member (no-member)
make: *** [Makefile:101: .pylint] Error 1
Original script exit code: 2
```

**Comment by Kami** [comment]
^ Fixed with the best option we have at this point (pylint ignore pragmas).

Once we drop support for Python 2, we can upgrade pylint to new version which knows how to handle those dynamic six attributes.

**Pull request merged**
