### PR TITLE
Do not post trigger for null payload webhooks

### PR DESCRIPTION
**Pull request by lakshmi-kannan**

### CODE REVIEW

**Comment by Kami** [comment]
Just curious - in what scenarios does Circle CI produce event with null payload?

**Comment by lakshmi-kannan** [comment]
@Kami It's not circle CI. It's out monitoring script that checks whether /webhooks/build/events URL is up and listening. We set a "St2-Event": "monitoring" header. One option is to check if that header is set and ignore but that would not apply to the community. This change is safe from both community perspective and our perspective.

**Comment by Kami** [comment]
Thanks for the clarification.

**Comment by Kami** [comment]
@lakshmi-kannan Just a heads up - our sensu check was broken after this change. It always returned "Ignored null webhook payload" error (caught by @armab after we reprovisioned cicd node).

Needed this change to fix it - https://github.com/StackStorm/st2puppet/commit/510c1639ffe66c1f2838848998fbabfb7b8e326e. The reason is we didn't send any `Content-Type` header so the check inside the sensor always failed (since the check explicitly checks for JSON body).

**Pull request merged**
